# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 681543796578675ca740666eeea319df1080c49d858088d57f128b8006c6e8c711751e71daa6f25f4edd8586f221e1bae42960e3858fbfaad31bcd4a912d1c61

test:
  secret_key_base: 3c22dd9eea2514b0d6c4a4813f9b8bd5a7ba967894c0f7fc111c28f4d07a54a4f9fa956683cdd91928f81e4b4d3e070d4ebafdeb3e0dfad0b322bb8b9c1163e3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
